# Generated by Django 3.2.12 on 2022-05-07 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('FileID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_modify_time', models.DateTimeField(auto_now=True)),
                ('commentFul', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('TeamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('comment_fileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
