# Generated by Django 4.0.3 on 2022-05-09 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('user', '0002_remove_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('dir_name', models.CharField(max_length=100)),
                ('dirID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('file_num', models.IntegerField(default=0)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'Directory',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('FileID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_modify_time', models.DateTimeField(auto_now=True)),
                ('commentFul', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('isDelete', models.BooleanField(default=False)),
                ('TeamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
                ('dirID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.directory')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'File',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('comment_fileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
