# Generated by Django 3.2.12 on 2022-05-11 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_isperson'),
        ('file', '0002_alter_file_isdir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='TeamID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
    ]
