# Generated by Django 3.2.12 on 2022-05-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20220511_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='fatherId',
            new_name='fatherID',
        ),
    ]
