# Generated by Django 4.0.3 on 2022-05-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_alter_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
