# Generated by Django 3.2.12 on 2022-05-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.CharField(max_length=65535, null=True),
        ),
    ]
