# Generated by Django 3.2.12 on 2022-05-28 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_root_file'),
        ('file', '0011_alter_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='using',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='using', to='user.user'),
        ),
        migrations.CreateModel(
            name='TeamFile_Perm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm', models.IntegerField(default=0)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file.file')),
            ],
        ),
    ]
