# Generated by Django 3.2.12 on 2022-05-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0012_auto_20220529_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='team_perm',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TeamFile_Perm',
        ),
    ]
