# Generated by Django 4.0.3 on 2022-06-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0013_auto_20220529_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
