# Generated by Django 3.2.12 on 2022-06-08 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0016_alter_file_last_read_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_share_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm', models.IntegerField()),
                ('link', models.CharField(max_length=20)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
            ],
        ),
    ]
