# Generated by Django 4.0.3 on 2022-06-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0017_file_share_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('m_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=100, unique=True)),
                ('m_content', models.CharField(max_length=65535, null=True)),
            ],
        ),
    ]
