# Generated by Django 3.2.12 on 2022-04-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0003_alter_article_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default="2000-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='lastEditTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
