# Generated by Django 3.2.12 on 2022-04-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0004_auto_20220412_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='lastEditTime',
        ),
    ]
