# Generated by Django 3.2.12 on 2022-04-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0005_remove_article_lastedittime'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lastEditTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
