# Generated by Django 3.2.12 on 2022-05-07 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50)),
                ('team_avatar', models.ImageField(upload_to='team_avatar')),
                ('managerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
