# Generated by Django 3.2.12 on 2022-05-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_auto_20220511_2150'),
        ('team', '0002_team_isperson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='managerID',
            new_name='manager',
        ),
        migrations.RemoveField(
            model_name='team',
            name='isPerson',
        ),
        migrations.AddField(
            model_name='team',
            name='team_root_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xx', to='file.file'),
        ),
    ]
