# Generated by Django 3.2.12 on 2022-05-23 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
