# Generated by Django 3.2.5 on 2022-05-01 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='avatar')),
                ('nickname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50)),
                ('team_avatar', models.ImageField(upload_to='team_avatar')),
                ('managerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diamond.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_send_time', models.DateTimeField(auto_now_add=True)),
                ('msg_contend', models.TextField()),
                ('msg_isRead', models.BooleanField(default=False)),
                ('msg_userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diamond.user')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('FileID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_modify_time', models.DateTimeField(auto_now=True)),
                ('commentFul', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('TeamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diamond.team')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diamond.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('comment_fileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diamond.file')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diamond.user')),
            ],
        ),
    ]
