# Generated by Django 3.2.12 on 2022-05-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='root_dir',
            field=models.IntegerField(default=0),
        ),
    ]
