# Generated by Django 3.2.12 on 2022-05-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_root_dir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='root_dir',
            new_name='root_file',
        ),
    ]
