# Generated by Django 3.2.12 on 2022-05-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_auto_20220511_2150'),
        ('user', '0006_alter_user_root_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='root_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yy', to='file.file'),
        ),
    ]
