# Generated by Django 4.0.3 on 2022-05-20 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_alter_user_root_file'),
        ('file', '0010_comment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='TagFile',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favourite.tag')),
            ],
        ),
    ]
