# Generated by Django 4.0.3 on 2022-06-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0002_tagfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_color',
            field=models.CharField(default='255', max_length=30),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_details',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
