# Generated by Django 4.0.3 on 2022-06-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0005_alter_tag_tag_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_details',
            field=models.CharField(default='这是标签的简介，你可以修改它', max_length=100, null=True),
        ),
    ]
